language: c
sudo: enabled
os:
  - linux
addons:
  ssh_known_hosts:
    - github.com
    - git.coding.net
  apt:
    packages: [gcc-multilib,nasm,upx,p7zip-full,zip,autoconf,automake,make,patch,npm]
    
before_install:
  - git config --global user.name "chenall"
  - git config --global user.email "chenall.cn@gmail.com"
#  - sudo apt-get update -y
#  - sudo apt-get install bison curl flex git gnupg git-core gperf build-essential zip curl
#  - sudo apt-get install build-essential autoconf automake make patch git gcc-multilib
#  - sudo apt-get install p7zip-full zip 

before_script:
# Download the toolchain
#  - git clone https://github.com/techdro-id/aarch64-linux-android -b snapshot $HOME/kernel/toolchain/snapshot
#  - git clone https://github.com/techdro-id/stormguard-kernel $HOME/kernel/stormguard
#  - git clone https://github.com/techdro-id/AnyKernel2 -b zImage $HOME/kernel/anykernel/zImage
#  - git clone https://github.com/techdro-id/zip $HOME/kernel/files/mido
   - git clone --depth=1 git://git.ipxe.org/ipxe.git

script:
  - ./build

after_success:
  - wget -O ~/site.7z http://dl.grub4dos.chenall.net/site.7z && 7z x -o$HOME ~/site.7z
  - ~/site/grub4dos.sh

notifications:
  email:
    recipents:
      - chenall.cn@gmail.com
    on_failure: never
